/*
 * TurboSMTP Public APIs
 *
 * This document describes all public turboSMTP v2 API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via API Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.  - --     
 *
 * The version of the OpenAPI document: 1.0.0-oas3
 * Contact: andrea@turbo-smtp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using API.TurboSMTP.Client;
using API.TurboSMTP.Api;
// uncomment below to import models
//using API.TurboSMTP.Model;

namespace API.TurboSMTP.Test.Api
{
    /// <summary>
    ///  Class for testing AuthenticationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AuthenticationApiTests : IDisposable
    {
        private AuthenticationApi instance;

        public AuthenticationApiTests()
        {
            instance = new AuthenticationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AuthenticationApi
            //Assert.IsType<AuthenticationApi>(instance);
        }

        /// <summary>
        /// Test AuthenticationLogin
        /// </summary>
        [Fact]
        public void AuthenticationLoginTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthenticationLoginRequestBody authenticationLoginRequestBody = null;
            //var response = instance.AuthenticationLogin(authenticationLoginRequestBody);
            //Assert.IsType<AuthenticationLoginSucessResponsetBody>(response);
        }

        /// <summary>
        /// Test AuthenticationLogout
        /// </summary>
        [Fact]
        public void AuthenticationLogoutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AuthenticationLogout();
            //Assert.IsType<CommonMessageResponseBody>(response);
        }

        /// <summary>
        /// Test ChangePassword
        /// </summary>
        [Fact]
        public void ChangePasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChangePasswordRequestBody changePasswordRequestBody = null;
            //var response = instance.ChangePassword(changePasswordRequestBody);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test CheckValidityTokenResetPassword
        /// </summary>
        [Fact]
        public void CheckValidityTokenResetPasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string token = null;
            //var response = instance.CheckValidityTokenResetPassword(token);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test SendSecretTokenResetPassword
        /// </summary>
        [Fact]
        public void SendSecretTokenResetPasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendSecretTokenResetPasswordRequestBody sendSecretTokenResetPasswordRequestBody = null;
            //var response = instance.SendSecretTokenResetPassword(sendSecretTokenResetPasswordRequestBody);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test UpdateResetPassword
        /// </summary>
        [Fact]
        public void UpdateResetPasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateResetPasswordRequestBody updateResetPasswordRequestBody = null;
            //var response = instance.UpdateResetPassword(updateResetPasswordRequestBody);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }
    }
}
