/*
 * TurboSMTP Public APIs
 *
 * This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.       
 *
 * The version of the OpenAPI document: 2.0.0-oas3
 * Contact: api@turbo-smtp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using API.TurboSMTP.Client;
using API.TurboSMTP.Api;
// uncomment below to import models
//using API.TurboSMTP.Model;

namespace API.TurboSMTP.Test.Api
{
    /// <summary>
    ///  Class for testing AlertsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AlertsApiTests : IDisposable
    {
        private AlertsApi instance;

        public AlertsApiTests()
        {
            instance = new AlertsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AlertsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AlertsApi
            //Assert.IsType<AlertsApi>(instance);
        }

        /// <summary>
        /// Test CreateAlert
        /// </summary>
        [Fact]
        public void CreateAlertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AlertBase alertBase = null;
            //var response = instance.CreateAlert(alertBase);
            //Assert.IsType<Alert>(response);
        }

        /// <summary>
        /// Test DeleteAlert
        /// </summary>
        [Fact]
        public void DeleteAlertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.DeleteAlert(id);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test GetAlert
        /// </summary>
        [Fact]
        public void GetAlertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.GetAlert(id);
            //Assert.IsType<Alert>(response);
        }

        /// <summary>
        /// Test GetAlerts
        /// </summary>
        [Fact]
        public void GetAlertsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAlerts();
            //Assert.IsType<AlertListSucessResponsetBody>(response);
        }

        /// <summary>
        /// Test UpdateAlert
        /// </summary>
        [Fact]
        public void UpdateAlertTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //AlertBase alertBase = null;
            //var response = instance.UpdateAlert(id, alertBase);
            //Assert.IsType<Alert>(response);
        }
    }
}
