/*
 * TurboSMTP Public APIs
 *
 * This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.       
 *
 * The version of the OpenAPI document: 2.0.0-oas3
 * Contact: api@turbo-smtp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using API.TurboSMTP.Client;
using API.TurboSMTP.Api;
// uncomment below to import models
//using API.TurboSMTP.Model;

namespace API.TurboSMTP.Test.Api
{
    /// <summary>
    ///  Class for testing SubaccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SubaccountsApiTests : IDisposable
    {
        private SubaccountsApi instance;

        public SubaccountsApiTests()
        {
            instance = new SubaccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubaccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SubaccountsApi
            //Assert.IsType<SubaccountsApi>(instance);
        }

        /// <summary>
        /// Test CheckIfAccountEmailExists
        /// </summary>
        [Fact]
        public void CheckIfAccountEmailExistsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string email = null;
            //var response = instance.CheckIfAccountEmailExists(email);
            //Assert.IsType<CommmonResultResponseBody>(response);
        }

        /// <summary>
        /// Test CreateSubaccount
        /// </summary>
        [Fact]
        public void CreateSubaccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SubaccountCreateRequest subaccountCreateRequest = null;
            //var response = instance.CreateSubaccount(subaccountCreateRequest);
            //Assert.IsType<Subaccount>(response);
        }

        /// <summary>
        /// Test DeleteLogoFile
        /// </summary>
        [Fact]
        public void DeleteLogoFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeleteLogoFile();
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test GetActivePlan
        /// </summary>
        [Fact]
        public void GetActivePlanTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.GetActivePlan(id);
            //Assert.IsType<SubaccountActivePlan>(response);
        }

        /// <summary>
        /// Test GetAgencySettings
        /// </summary>
        [Fact]
        public void GetAgencySettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetAgencySettings();
            //Assert.IsType<AgencySettings>(response);
        }

        /// <summary>
        /// Test GetLogoFile
        /// </summary>
        [Fact]
        public void GetLogoFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetLogoFile();
            //Assert.IsType<Logo>(response);
        }

        /// <summary>
        /// Test GetSubaccountDetails
        /// </summary>
        [Fact]
        public void GetSubaccountDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.GetSubaccountDetails(id);
            //Assert.IsType<Subaccount>(response);
        }

        /// <summary>
        /// Test GetSubaccounts
        /// </summary>
        [Fact]
        public void GetSubaccountsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? limit = null;
            //string filterByEmail = null;
            //bool? filterByActive = null;
            //List<string> filterByIP = null;
            //string orderby = null;
            //OrderType ordertype = null;
            //var response = instance.GetSubaccounts(page, limit, filterByEmail, filterByActive, filterByIP, orderby, ordertype);
            //Assert.IsType<SubAccountListSucessResponsetBody>(response);
        }

        /// <summary>
        /// Test SubaccountAuthenticationLogin
        /// </summary>
        [Fact]
        public void SubaccountAuthenticationLoginTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Email1 email1 = null;
            //var response = instance.SubaccountAuthenticationLogin(email1);
            //Assert.IsType<AuthenticationLoginSucessResponsetBody>(response);
        }

        /// <summary>
        /// Test UpdateAgencySettings
        /// </summary>
        [Fact]
        public void UpdateAgencySettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BaseAgencySettings baseAgencySettings = null;
            //var response = instance.UpdateAgencySettings(baseAgencySettings);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }

        /// <summary>
        /// Test UpdateSubaccountDetails
        /// </summary>
        [Fact]
        public void UpdateSubaccountDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //SubaccountUpdateRequest subaccountUpdateRequest = null;
            //var response = instance.UpdateSubaccountDetails(id, subaccountUpdateRequest);
            //Assert.IsType<Subaccount>(response);
        }

        /// <summary>
        /// Test UpdateSubaccountSMTPLimit
        /// </summary>
        [Fact]
        public void UpdateSubaccountSMTPLimitTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //SubaccountSMTPLimit subaccountSMTPLimit = null;
            //var response = instance.UpdateSubaccountSMTPLimit(id, subaccountSMTPLimit);
            //Assert.IsType<SubaccountActivePlan>(response);
        }

        /// <summary>
        /// Test UpdateSubaccountStatus
        /// </summary>
        [Fact]
        public void UpdateSubaccountStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //SubaccountActiveStatus subaccountActiveStatus = null;
            //var response = instance.UpdateSubaccountStatus(id, subaccountActiveStatus);
            //Assert.IsType<SubaccountActivePlan>(response);
        }

        /// <summary>
        /// Test UploadLogoFile
        /// </summary>
        [Fact]
        public void UploadLogoFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //var response = instance.UploadLogoFile(file);
            //Assert.IsType<CommonSuccessResponseBody>(response);
        }
    }
}
